### ISSUE TITLE
Support Python3

### ISSUE THREAD

**Issue by aqjune** [SUSE/cpuset#33]
Is there plan for supporting Python3?

It seems making `make`, `make install` run with Python3 is straightforward, but running it raises the following error:

```
$ cset                                                              
Traceback (most recent call last):                                                           
  File "/home/sflab/bin/cset", line 44, in <module>                                          
    from cpuset.main import main                                                             
  File "/home/sflab/lib/python3.6/site-packages/cpuset/main.py", line 7, in <module>         
    from future import standard_library                                                      
ModuleNotFoundError: No module named 'future'                                                
```

**Comment by thiagokokada** [comment]
It is supported, but you need to have `python-future` library installed: https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/cpuset/default.nix#L13

(`configparser` is not needed for Python 3, just Python 2, but it is forwarding compatible).
