### ISSUE TITLE
Not working with kernel 6.12

### ISSUE THREAD

**Issue by olm52** [SUSE/cpuset#49]
cpuset is not working with kernel 6.12

Error message:

mount: /cpusets: unknown filesystem type 'cpuset'.
       dmesg(1) may have more information after failed mount system call.

I tried also to add 
systemd.unified_cgroup_hierarchy=0
to kernel line, but the system does not even boot.

Archlinux updated, systemd version 256.8

It was working with kernel 6.11.1

**Comment by Werkov** [comment]
The cpuset utility supports only cgroup v1.
The new kernel introduced `CONFIG_CPUSETS_V1` which defaults to `N` (as a gradual move from v1 to v2) hence you'd need a kernel built with changed configuration (or configure cpuset v2 [e.g. with systemd](https://github.com/SUSE/cpuset/issues/40#issuecomment-833479062))

Does any of the above solve the issue? (And thanks for the report.)

**Comment by Werkov** [comment]
> That is not enough however.

FTR, it should be possible to use only cpuset controller on v1 and the rest of system with v2 (no forcing of v1 to systemd), i.e. the setup that used to work with 6.11 for you.
